language: cpp
compiler:
  - gcc
python:
  - "2.7"

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo add-apt-repository -y ppa:george-edison55/precise-backports
  - sudo apt-get remove -qq cmake cmake-data
  - sudo apt-get autoremove -qq
  - sudo apt-get update -y -qq
  - sudo apt-get install -y -qq g++-6 boost1.55 cmake-data cmake
  - sudo update-alternatives --install /usr/bin/g++  g++  /usr/bin/g++-6  90
  - sudo update-alternatives --install /usr/bin/gcc  gcc  /usr/bin/gcc-6  90
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-6 90
  - sudo apt-get install -y -qq zlib1g-dev

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=DEBUG -DBUILD_TESTS=ON ..

script:
  - make -j 1
  - make test

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - bo.han@umassmed.edu
    on_success: change
    on_failure: always
